name: Get latest V8 stable version

on:
  schedule:
  - cron: '0 */12 * * *'
  push:
    branches: [ main ]
    paths:
    - 'get_version.js'
    - '.github/workflows/get_version.yml'
  workflow_dispatch:

permissions: write-all

jobs:
  version_finder:
    name: Get version number
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
       node-version: 18
    - name: "Get version"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        cd $GITHUB_WORKSPACE
        npm i @actions/github@2.2.0
        node ./get_version.js
